Mp add authorization
Ritumka/industrial-auth-1 pull request #1
Opened 2024-10-29 01:49 UTC by Ritumka

2024-10-29 01:57 UTC, tluu5 reviewed
great job adding before_action on the photos_controller

2024-10-29 01:59 UTC, tluu5 reviewed
I like how you wrote the if statement for the current_user, allowing only the user to see the show page.

2024-10-29 02:00 UTC, tluu5 approved these changes

2024-11-01 15:42 UTC, merrillhuang requested changes

2024-11-01 15:42 UTC, merrillhuang commented on config/routes.rb
Good job excluding comments index route.

2024-11-01 15:42 UTC, merrillhuang commented on app/controllers/comments_controller.rb
A user can still edit and delete comments that don't belong to them. If I visit comments/4/edit as Alice, I can still edit the comment even though it belongs to Aubrey.

2024-11-01 15:42 UTC, merrillhuang commented on app/controllers/follow_requests_controller.rb
Users can't accept or reject follow requests when they are recipients. Check /manda when logged in as Alice and try accepting or rejecting the follow request.

2024-11-05 05:31 UTC, marywebby requested changes
Great job!! Please fix the accepting and rejecting functionality of the follow requests, and re-request me when you're done!

2024-11-05 05:31 UTC, marywebby commented on app/controllers/comments_controller.rb
> +    @comment = Comment.find(params.fetch(:id))
good job implementing the delete comment section here.

2024-11-05 05:31 UTC, marywebby commented on app/controllers/comments_controller.rb
> +  before_action :is_a_comment_author, only: [:destroy]
it looks like edit is still working here as well, but maybe make sure to include `:edit` on the `:is_a_comment_author`

2024-11-05 05:31 UTC, marywebby commented on app/controllers/follow_requests_controller.rb
>  class FollowRequestsController < ApplicationController
Also agree with what Merrill said, the user cannot accept or reject the pending follow requests for them.

2024-11-05 05:31 UTC, marywebby commented on app/controllers/likes_controller.rb
> +  before_action :ensure_current_user_is_owner, only: [:destroy, :update, :edit]
Good job implementing likes

2024-11-05 05:31 UTC, marywebby commented on app/controllers/photos_controller.rb
> +    redirect_back(fallback_location: root_url, notice: "Nice try, but that is not your photo.")
very funny

2024-11-05 22:16 UTC, Ritumka commented on app/controllers/follow_requests_controller.rb
>  class FollowRequestsController < ApplicationController
Fixed!

2024-11-05 22:17 UTC, Ritumka commented on app/controllers/follow_requests_controller.rb
Fixed!

2024-11-05 22:18 UTC, merrillhuang approved these changes
Looks good!

2024-11-06 16:59 UTC, marywebby approved these changes
Great work!!!

2024-11-06 17:12 UTC, merged