add-pundit
Ritumka/industrial-auth-1 pull request #3
Opened 2024-10-29 16:10 UTC by Ritumka

2024-10-29 21:33 UTC, tluu5 reviewed
great job adding the Pundit gem and the user_not_authorized method

2024-10-29 21:34 UTC, tluu5 reviewed
Added if statement on user#show

2024-10-29 21:35 UTC, tluu5 approved these changes
You are ready.

2024-10-30 18:42 UTC, armstrca commented
In the real world, branches are rarely created off of other branches. They're usually just branched directly off of main and intended to merge back directly to main.

In this context, it kind of makes sense to branch the way you've done here, because different people are reviewing both PRs and this one is dependent on the content of the earlier PR. So if the earlier one hasn't merged to main yet, I don't have to sort through as many changes that are already getting looked at in the other PR by Mary  (`mp-add-pundit` has more changes compared to `main` than compared to `mp-add-authorization`).

That all said, it would be best practice to merge the previous PR to main first, and then change this PR so that it merges into `main` rather than `mp-add-authorization` (that's also what the official assignment requirement is).

2024-10-30 20:18 UTC, armstrca commented on app/controllers/photos_controller.rb
> +  # before_action :ensure_user_is_authorized, only: [:show]
Removed commented-out code

2024-10-31 01:11 UTC, Ritumka commented
> In the real world, branches are rarely created off of other branches. They're usually just branched directly off of main and intended to merge back directly to main.
> 
> In this context, it kind of makes sense to branch the way you've done here, because different people are reviewing both PRs and this one is dependent on the content of the earlier PR. So if the earlier one hasn't merged to main yet, I don't have to sort through as many changes that are already getting looked at in the other PR by Mary (`mp-add-pundit` has more changes compared to `main` than compared to `mp-add-authorization`).
> 
> That all said, it would be best practice to merge the previous PR to main first, and then change this PR so that it merges into `main` rather than `mp-add-authorization` (that's also what the official assignment requirement is).

This PR has only commits related to Pundit assignment and it compares `mp-add-pundit` branch with `mp-add-authorization` (not `main`). But I got you! Thank you.

2024-10-31 01:12 UTC, Ritumka commented on app/controllers/photos_controller.rb
> +  # before_action :ensure_user_is_authorized, only: [:show]
Done!

2024-11-01 16:48 UTC, armstrca requested changes
The assignment does technically require this to be a merge to main, so just change the commit to `main` from `mp-add-pundit` and resolve any merge conflicts that might come up.

2024-11-05 18:06 UTC, armstrca approved these changes

2024-11-06 17:14 UTC, merged